import streamlit as st
import pandas as pd
import csv
import random

# ----------------------------------------
# Function to read the CSV file
# ----------------------------------------
def read_csv_to_dict(file_path):
    program_ratings = {}
    with open(file_path, mode='r', newline='') as file:
        reader = csv.reader(file)
        header = next(reader)
        for row in reader:
            program = row[0]
            ratings = [float(x) for x in row[1:]]
            program_ratings[program] = ratings
    return program_ratings

# ----------------------------------------
# Fitness Function
# ----------------------------------------
def fitness_function(schedule, ratings):
    total_rating = 0
    for time_slot, program in enumerate(schedule):
        total_rating += ratings[program][time_slot]
    return total_rating

# ----------------------------------------
# Genetic Algorithm Functions
# ----------------------------------------
def crossover(schedule1, schedule2):
    crossover_point = random.randint(1, len(schedule1) - 2)
    child1 = schedule1[:crossover_point] + schedule2[crossover_point:]
    child2 = schedule2[:crossover_point] + schedule1[crossover_point:]
    return child1, child2

def mutate(schedule, all_programs):
    mutation_point = random.randint(0, len(schedule) - 1)
    new_program = random.choice(all_programs)
    schedule[mutation_point] = new_program
    return schedule

def genetic_algorithm(initial_schedule, ratings, generations, population_size, crossover_rate, mutation_rate, elitism_size, all_programs):
    population = [initial_schedule]
    for _ in range(population_size - 1):
        random_schedule = initial_schedule.copy()
        random.shuffle(random_schedule)
        population.append(random_schedule)

    for generation in range(generations):
        new_population = []

        # Elitism
        population.sort(key=lambda schedule: fitness_function(schedule, ratings), reverse=True)
        new_population.extend(population[:elitism_size])

        while len(new_population) < population_size:
            parent1, parent2 = random.choices(population, k=2)
            if random.random() < crossover_rate:
                child1, child2 = crossover(parent1, parent2)
            else:
                child1, child2 = parent1.copy(), parent2.copy()

            if random.random() < mutation_rate:
                child1 = mutate(child1, all_programs)
            if random.random() < mutation_rate:
                child2 = mutate(child2, all_programs)

            new_population.extend([child1, child2])

        population = new_population

    best_schedule = max(population, key=lambda schedule: fitness_function(schedule, ratings))
    return best_schedule

# ----------------------------------------
# Streamlit Interface
# ----------------------------------------
st.title("📅 Genetic Algorithm Scheduler")
st.markdown("""
This app allows users to experiment with **Crossover Rate (CO_R)** and **Mutation Rate (MUT_R)** 
to see how they affect the final schedule generated by a Genetic Algorithm.
""")

# Sidebar inputs for parameters (Part 3)
st.sidebar.header("Set Genetic Algorithm Parameters")

CO_R = st.sidebar.slider("Crossover Rate (CO_R)", 0.0, 0.95, 0.8, 0.01)
MUT_R = st.sidebar.slider("Mutation Rate (MUT_R)", 0.01, 0.05, 0.02, 0.01)

st.sidebar.write("Crossover Rate:", CO_R)
st.sidebar.write("Mutation Rate:", MUT_R)

# Load data
file_path = "program_ratings_modified.csv"
ratings = read_csv_to_dict(file_path)
all_programs = list(ratings.keys())
all_time_slots = list(range(6, 6 + len(all_programs)))  # time slots: 6 AM onwards

# Run algorithm when user clicks button
if st.button("Run Genetic Algorithm"):
    initial_schedule = all_programs.copy()
    random.shuffle(initial_schedule)

    best_schedule = genetic_algorithm(
        initial_schedule,
        ratings,
        generations=100,
        population_size=50,
        crossover_rate=CO_R,
        mutation_rate=MUT_R,
        elitism_size=2,
        all_programs=all_programs
    )

    total_fitness = fitness_function(best_schedule, ratings)

    # Display schedule in table (Part 4)
    st.subheader("✅ Generated Schedule")
    df = pd.DataFrame({
        "Time Slot": [f"{t}:00" for t in all_time_slots],
        "Program": best_schedule
    })
    st.table(df)

    st.success(f"Total Ratings (Fitness Score): {total_fitness:.2f}")

